import { Res } from 'model/backend';
import { Meeting, MeetingRegistrant, RecordingUrl } from 'model/backend/zoom-data';

export const meetingsMock: Meeting[] = [
  {
    cohort_id: 89,
    details: {
      agenda: '',
      assistant_id: '',
      created_at: '2021-09-15T00:24:50Z',
      duration: 60,
      encrypted_password: 'Qk9TeVBkR09VNXNFUitvaVoyMUJuQT09',
      h323_password: '6213523249',
      host_email: 'hello@seekingsafety.org',
      host_id: 'JgMN4HPbQsCbShY2FMF45w',
      id: 83729042685,
      join_url: 'https://us06web.zoom.us/j/83729042685?pwd=Qk9TeVBkR09VNXNFUitvaVoyMUJuQT09',
      password: 'Compassion',
      pre_schedule: false,
      pstn_password: '6213523249',
      registration_url: 'https://us06web.zoom.us/meeting/register/tZcqdeCoqjksEtGtjDepuy4dEntjnsdTVIfr',
      settings: {
        allow_multiple_devices: true,
        alternative_hosts: '',
        alternative_hosts_email_notification: true,
        approval_type: 0,
        approved_or_denied_countries_or_regions: {
          enable: false,
        },
        audio: 'both',
        auto_recording: 'cloud',
        breakout_room: {
          enable: false,
        },
        close_registration: false,
        cn_meeting: false,
        contact_email: 'hello@seekingsafety.org',
        contact_name: 'Seeking Safety',
        device_testing: false,
        encryption_type: 'enhanced_encryption',
        enforce_login: false,
        enforce_login_domains: '',
        global_dial_in_countries: ['US'],
        global_dial_in_numbers: [
          {
            city: 'Washington DC',
            country: 'US',
            country_name: 'US',
            number: '+1 3017158592',
            type: 'toll',
          },
          {
            city: 'Chicago',
            country: 'US',
            country_name: 'US',
            number: '+1 3126266799',
            type: 'toll',
          },
          {
            city: 'New York',
            country: 'US',
            country_name: 'US',
            number: '+1 6465588656',
            type: 'toll',
          },
          {
            city: 'Tacoma',
            country: 'US',
            country_name: 'US',
            number: '+1 2532158782',
            type: 'toll',
          },
          {
            city: 'Houston',
            country: 'US',
            country_name: 'US',
            number: '+1 3462487799',
            type: 'toll',
          },
          {
            city: 'Denver',
            country: 'US',
            country_name: 'US',
            number: '+1 7207072699',
            type: 'toll',
          },
        ],
        host_video: false,
        in_meeting: false,
        jbh_time: 0,
        join_before_host: true,
        meeting_authentication: false,
        mute_upon_entry: false,
        participant_video: false,
        registrants_confirmation_email: false,
        registrants_email_notification: false,
        request_permission_to_unmute_participants: false,
        show_share_button: true,
        use_pmi: false,
        waiting_room: false,
        watermark: false,
      },
      start_time: '2021-10-23T19:00:00Z',
      start_url:
        'https://us06web.zoom.us/s/83729042685?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMSIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJhdWQiOiJjbGllbnRzbSIsInVpZCI6IkpnTU40SFBiUXNDYlNoWTJGTUY0NXciLCJpc3MiOiJ3ZWIiLCJzdHkiOjEwMCwid2NkIjoidXMwNiIsImNsdCI6MCwic3RrIjoidXVSQjhCaXpGQ0txVmlSNXBaaGx0bDVUVlFyRnh2NW92eHVKQVNrbkdDYy5CZ1lnVG5SRFYwRkhOVXRwTUZaMlYzVkpMMXBRYzIxcllUVmpUamg1Vmtsd1VtZEFNak5oWm1RME1tTm1OMlV3WWpZMk0yWmtOemxsWXpKak9UZGxOVEJsWlRrNE9HWTNOakkyTXpWbFpETmlPR00zTnpaa05XSmhaV0pqT0RnM05EQXhaQUFNTTBOQ1FYVnZhVmxUTTNNOUFBUjFjekEyQUFBQmUtYjRzWTRBRW5VQUFBQSIsImV4cCI6MTYzMTY3NDg2MywiaWF0IjoxNjMxNjY3NjYzLCJhaWQiOiItZnhXRU5McFJqLURxa00wa25PTkZ3IiwiY2lkIjoiIn0.Y3McxPm3_Wn4A8bed_LNh_ZC9AkgCEUu390RuKnA5-4',
      status: 'waiting',
      timezone: 'America/New_York',
      topic: 'Compassion',
      type: 2,
      uuid: 'WsRMhrP7SCa/UHu1V0NXWA==',
    },
    feedback_url: 'https://docs.google.com/forms/d/e/1FAIpQLSciWFG7E1VYyxoWTY0J_cn8_Tuu12UY0ewPscjlkLykJgw5jg/viewform',
    id: 83729042685,
    topic_id: 32,
  },
  {
    cohort_id: 90,
    details: {
      agenda: '',
      assistant_id: '',
      created_at: '2021-09-15T21:27:32Z',
      duration: 60,
      encrypted_password: 'Vm84ZFJBVFNHWGZCY3h1RXh6RmJKUT09',
      h323_password: '500568',
      host_email: 'hello@seekingsafety.org',
      host_id: 'JgMN4HPbQsCbShY2FMF45w',
      id: 83447016097,
      join_url: 'https://us06web.zoom.us/j/83447016097?pwd=Vm84ZFJBVFNHWGZCY3h1RXh6RmJKUT09',
      password: 'Safety',
      pre_schedule: false,
      pstn_password: '500568',
      registration_url: 'https://us06web.zoom.us/meeting/register/tZcpc-6orz0qE9MoRI32TPgI6Wk-2sqEDZdm',
      settings: {
        allow_multiple_devices: true,
        alternative_hosts: '',
        alternative_hosts_email_notification: true,
        approval_type: 0,
        approved_or_denied_countries_or_regions: {
          enable: false,
        },
        audio: 'both',
        auto_recording: 'cloud',
        breakout_room: {
          enable: false,
        },
        close_registration: false,
        cn_meeting: false,
        contact_email: 'hello@seekingsafety.org',
        contact_name: 'Seeking Safety',
        device_testing: false,
        encryption_type: 'enhanced_encryption',
        enforce_login: false,
        enforce_login_domains: '',
        global_dial_in_countries: ['US'],
        global_dial_in_numbers: [
          {
            city: 'New York',
            country: 'US',
            country_name: 'US',
            number: '+1 6465588656',
            type: 'toll',
          },
          {
            city: 'Washington DC',
            country: 'US',
            country_name: 'US',
            number: '+1 3017158592',
            type: 'toll',
          },
          {
            city: 'Chicago',
            country: 'US',
            country_name: 'US',
            number: '+1 3126266799',
            type: 'toll',
          },
          {
            city: 'Denver',
            country: 'US',
            country_name: 'US',
            number: '+1 7207072699',
            type: 'toll',
          },
          {
            city: 'Tacoma',
            country: 'US',
            country_name: 'US',
            number: '+1 2532158782',
            type: 'toll',
          },
          {
            city: 'Houston',
            country: 'US',
            country_name: 'US',
            number: '+1 3462487799',
            type: 'toll',
          },
        ],
        host_video: false,
        in_meeting: false,
        jbh_time: 0,
        join_before_host: true,
        meeting_authentication: false,
        mute_upon_entry: false,
        participant_video: false,
        registrants_confirmation_email: false,
        registrants_email_notification: false,
        request_permission_to_unmute_participants: false,
        show_share_button: true,
        use_pmi: false,
        waiting_room: false,
        watermark: false,
      },
      start_time: '2021-09-19T18:00:00Z',
      start_url:
        'https://us06web.zoom.us/s/83447016097?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMSIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJhdWQiOiJjbGllbnRzbSIsInVpZCI6IkpnTU40SFBiUXNDYlNoWTJGTUY0NXciLCJpc3MiOiJ3ZWIiLCJzdHkiOjEwMCwid2NkIjoidXMwNiIsImNsdCI6MCwic3RrIjoiNHFyWW81eDJ0RHFqb3RIb2c5UFUtOFQyTkZaRlBGQm5laGg1UXlpMTJNMC5CZ1lnVG5SRFYwRkhOVXRwTUZaMlYzVkpMMXBRYzIxcllUVmpUamg1Vmtsd1VtZEFNak5oWm1RME1tTm1OMlV3WWpZMk0yWmtOemxsWXpKak9UZGxOVEJsWlRrNE9HWTNOakkyTXpWbFpETmlPR00zTnpaa05XSmhaV0pqT0RnM05EQXhaQUFNTTBOQ1FYVnZhVmxUTTNNOUFBUjFjekEyQUFBQmUtdG8ydUFBRW5VQUFBQSIsImV4cCI6MTYzMTc0OTMyMiwiaWF0IjoxNjMxNzQyMTIyLCJhaWQiOiItZnhXRU5McFJqLURxa00wa25PTkZ3IiwiY2lkIjoiIn0.Qfduk5P0eBRkzsGTamjnCj0vjXNVM5BRv5KiIl1GFpg',
      status: 'waiting',
      timezone: 'America/New_York',
      topic: 'Safety ',
      type: 2,
      uuid: 'mpV3yBPPRD6xSDY/6YxcVQ==',
    },
    feedback_url: 'https://docs.google.com/forms/d/e/1FAIpQLScL0utyHEOoguLlrk6bW5oSCtKbh-y8-2SrysXIE5Iyzighcw/viewform',
    id: 83447016097,
    topic_id: 26,
  },
  {
    cohort_id: 73,
    details: {
      agenda: '',
      assistant_id: '',
      created_at: '2021-04-13T19:48:23Z',
      duration: 60,
      encrypted_password: 'SmgxSi9GbkF0SEF0ajdyNjBrMldlUT09',
      h323_password: '8093998220',
      host_email: 'hello@seekingsafety.org',
      host_id: 'JgMN4HPbQsCbShY2FMF45w',
      id: 99108448642,
      join_url: 'https://zoom.us/j/99108448642?pwd=SmgxSi9GbkF0SEF0ajdyNjBrMldlUT09',
      password: 'Red and Gr',
      pstn_password: '8093998220',
      registration_url: 'https://zoom.us/meeting/register/tJ0sd-GsqjMsHtbTQZeWGvge_2ZkFZxroNuI',
      settings: {
        allow_multiple_devices: true,
        alternative_hosts: '',
        alternative_hosts_email_notification: true,
        approval_type: 0,
        approved_or_denied_countries_or_regions: {
          enable: false,
        },
        audio: 'both',
        auto_recording: 'cloud',
        breakout_room: {
          enable: false,
        },
        close_registration: false,
        cn_meeting: false,
        contact_email: 'hello@seekingsafety.org',
        contact_name: 'Seeking Safety',
        device_testing: false,
        encryption_type: 'enhanced_encryption',
        enforce_login: false,
        enforce_login_domains: '',
        global_dial_in_countries: ['US'],
        global_dial_in_numbers: [
          {
            country: 'US',
            country_name: 'US',
            number: '+1 6465588656',
            type: 'toll',
          },
          {
            country: 'US',
            country_name: 'US',
            number: '+1 3017158592',
            type: 'toll',
          },
          {
            country: 'US',
            country_name: 'US',
            number: '+1 3126266799',
            type: 'toll',
          },
          {
            country: 'US',
            country_name: 'US',
            number: '+1 6699009128',
            type: 'toll',
          },
          {
            country: 'US',
            country_name: 'US',
            number: '+1 2532158782',
            type: 'toll',
          },
          {
            country: 'US',
            country_name: 'US',
            number: '+1 3462487799',
            type: 'toll',
          },
        ],
        host_video: false,
        in_meeting: false,
        jbh_time: 0,
        join_before_host: true,
        meeting_authentication: false,
        mute_upon_entry: false,
        participant_video: false,
        registrants_confirmation_email: false,
        registrants_email_notification: false,
        request_permission_to_unmute_participants: false,
        show_share_button: true,
        use_pmi: false,
        waiting_room: false,
        watermark: false,
      },
      start_time: '2021-09-19T22:22:00Z',
      start_url:
        'https://zoom.us/s/99108448642?zak=eyJ6bV9za20iOiJ6bV9vMm0iLCJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJjbGllbnQiLCJ1aWQiOiJKZ01ONEhQYlFzQ2JTaFkyRk1GNDV3IiwiaXNzIjoid2ViIiwic3R5IjoxMDAsIndjZCI6ImF3MSIsImNsdCI6MCwic3RrIjoiNS1WRTFBOXlzODdzRTIzT21fcnpzbzY1VlBTSWhhRUpERGxFdnh5NnlvQS5CZ1lnVG5SRFYwRkhOVXRwTUZaMlYzVkpMMXBRYzIxcllUVmpUamg1Vmtsd1VtZEFNak5oWm1RME1tTm1OMlV3WWpZMk0yWmtOemxsWXpKak9UZGxOVEJsWlRrNE9HWTNOakkyTXpWbFpETmlPR00zTnpaa05XSmhaV0pqT0RnM05EQXhaQUFNTTBOQ1FYVnZhVmxUTTNNOUFBTmhkekVBQUFGNVdYRENvZ0FTZFFBQUFBIiwiZXhwIjoxNjIwNzEwNDMyLCJpYXQiOjE2MjA3MDMyMzIsImFpZCI6Ii1meFdFTkxwUmotRHFrTTBrbk9ORnciLCJjaWQiOiIifQ.2vn0O5Z6_M84f4lfeHgT3R-kbzemrKkWB2xoLNuxuLg',
      status: 'waiting',
      timezone: 'America/New_York',
      topic: 'Red and Green Flags',
      type: 2,
      uuid: 'SwY1gnEKQHepGt9SedD8pg==',
    },
    feedback_url: 'https://docs.google.com/forms/d/e/1FAIpQLSc11FQcOcXiY4jr6_hNXW65hu7NMk38vbaYPqku1-zfySBhWA/viewform',
    id: 99108448642,
    topic_id: 36,
  },
];

export const recordingUrlMock: Res<RecordingUrl> = {
  error: null,
  status: 'ok',
  url: 'https://us06web.zoom.us/rec/download/mswVMmMRDvl46YDuVsyEAFXNKrXqtYdFS_Z7qQOoqQFKPpxT8eCVSxZ0Zu3996Z9AKHGaEuYfApFdSVs.FFt8oPCTdPoDhvgu?access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDN2NMRWtDNlRZcUlkTldZbVdXbXRRIiwiZXhwIjoxNjMxNzk3OTM0LjUyODM5Nn0.h9VGFx8jVPAkqR1F7hWXwHpQjGMt8guRKSLD6o7XY5Q',
};

export const meetingRegistrantMock: MeetingRegistrant = {
  id: 93657658169,
  join_url:
    'https://us06web.zoom.us/w/93657658169?tk=wpgjsY2JNGO-pIsxO24O-KuD8TpweiY_xQ1KYawMLcY.DQMAAAAVzm5zORZLWXc5R0RMRFE0aUQtOVktX0s4ZktBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&pwd=ZEZneGRYVzQvRjhqOHhuRUx0ZkZ5dz09',
  registrant_id: 'KYw9GDLDQ4iD-9Y-_K8fKA',
  start_time: '2021-09-19T21:30:00Z',
  topic: 'Healthy Relationships',
};
