import { Progress } from 'model/backend/progress';

export const PROGRESS: { progress: Progress } = {
  progress: {
    count_topics_so_far: 2,
    daily_quest: {
      avg_cohort_quests: 0,
      my_quests: 1,
    },
    daily_quiz: {
      avg_cohort_quizzes: 4,
      my_quizzes: 11,
    },
    daily_safety_check: {
      avg_cohort_checks: 0,
      days: 1,
      my_checks: 1,
    },
    daily_safety_reflection: {
      avg_cohort_reflections: 0,
      my_reflections: 0,
    },
    learn_reflections: {
      avg_cohort_reflections: 0,
      my_reflections: 1,
    },
    my_safe_place_posts: {
      avg_cohort_posts: 2,
      my_posts: 6,
    },
    prepare_for_a_trigger: {
      avg_cohort_trigger_preps: 0,
      my_trigger_preps: 0,
    },
    safety_boomerang: {
      avg_cohort_boomerangs: 0,
      my_boomerangs: 0,
    },
    safety_plan_check: {
      avg_cohort_checks: 0,
      my_checks: 0,
    },
    safety_surprise: {
      avg_cohort_surprises: 0,
      my_surprises: 0,
    },
    set_up_safety_tools: {
      safe_unsafe_picture: false,
      safety_plan_wizard: false,
      talk_to_safe_self: true,
    },
    social_feed_posts: {
      avg_cohort_posts: 0,
      my_posts: 0,
    },
    trigger_severity: [
      {
        date: 'Mon, 26 Jul 2021 00:00:00 GMT',
        dow: 0,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Tue, 27 Jul 2021 00:00:00 GMT',
        dow: 1,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Wed, 28 Jul 2021 00:00:00 GMT',
        dow: 2,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Thu, 29 Jul 2021 00:00:00 GMT',
        dow: 3,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Fri, 30 Jul 2021 00:00:00 GMT',
        dow: 4,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Sat, 31 Jul 2021 00:00:00 GMT',
        dow: 5,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Sun, 01 Aug 2021 00:00:00 GMT',
        dow: 6,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Mon, 02 Aug 2021 00:00:00 GMT',
        dow: 0,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Tue, 03 Aug 2021 00:00:00 GMT',
        dow: 1,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Wed, 04 Aug 2021 00:00:00 GMT',
        dow: 2,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Thu, 05 Aug 2021 00:00:00 GMT',
        dow: 3,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Fri, 06 Aug 2021 00:00:00 GMT',
        dow: 4,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Sat, 07 Aug 2021 00:00:00 GMT',
        dow: 5,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Sun, 08 Aug 2021 00:00:00 GMT',
        dow: 6,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Mon, 09 Aug 2021 00:00:00 GMT',
        dow: 0,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Tue, 10 Aug 2021 00:00:00 GMT',
        dow: 1,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Wed, 11 Aug 2021 00:00:00 GMT',
        dow: 2,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Thu, 12 Aug 2021 00:00:00 GMT',
        dow: 3,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Fri, 13 Aug 2021 00:00:00 GMT',
        dow: 4,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Sat, 14 Aug 2021 00:00:00 GMT',
        dow: 5,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Sun, 15 Aug 2021 00:00:00 GMT',
        dow: 6,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Mon, 16 Aug 2021 00:00:00 GMT',
        dow: 0,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Tue, 17 Aug 2021 00:00:00 GMT',
        dow: 1,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Wed, 18 Aug 2021 00:00:00 GMT',
        dow: 2,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Thu, 19 Aug 2021 00:00:00 GMT',
        dow: 3,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Fri, 20 Aug 2021 00:00:00 GMT',
        dow: 4,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Sat, 21 Aug 2021 00:00:00 GMT',
        dow: 5,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Sun, 22 Aug 2021 00:00:00 GMT',
        dow: 6,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Mon, 23 Aug 2021 00:00:00 GMT',
        dow: 0,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Tue, 24 Aug 2021 00:00:00 GMT',
        dow: 1,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Wed, 25 Aug 2021 00:00:00 GMT',
        dow: 2,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Thu, 26 Aug 2021 00:00:00 GMT',
        dow: 3,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Fri, 27 Aug 2021 00:00:00 GMT',
        dow: 4,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Sat, 28 Aug 2021 00:00:00 GMT',
        dow: 5,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Sun, 29 Aug 2021 00:00:00 GMT',
        dow: 6,
        severity: 1,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Mon, 30 Aug 2021 00:00:00 GMT',
        dow: 0,
        severity: 0,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        date: 'Tue, 31 Aug 2021 00:00:00 GMT',
        dow: 1,
        severity: 0,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        date: 'Wed, 01 Sep 2021 00:00:00 GMT',
        dow: 2,
        severity: 0,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        date: 'Thu, 02 Sep 2021 00:00:00 GMT',
        dow: 3,
        severity: 0,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        date: 'Fri, 03 Sep 2021 00:00:00 GMT',
        dow: 4,
        severity: 0,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        date: 'Sat, 04 Sep 2021 00:00:00 GMT',
        dow: 5,
        severity: 0,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        date: 'Sun, 05 Sep 2021 00:00:00 GMT',
        dow: 6,
        severity: 0,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        date: 'Mon, 06 Sep 2021 00:00:00 GMT',
        dow: 0,
        severity: 0,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        date: 'Tue, 07 Sep 2021 00:00:00 GMT',
        dow: 1,
        severity: 0,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        date: 'Wed, 08 Sep 2021 00:00:00 GMT',
        dow: 2,
        severity: 0,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        date: 'Thu, 09 Sep 2021 00:00:00 GMT',
        dow: 3,
        severity: 0,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        date: 'Fri, 10 Sep 2021 00:00:00 GMT',
        dow: 4,
        severity: 0,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        date: 'Sat, 11 Sep 2021 00:00:00 GMT',
        dow: 5,
        severity: 0,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        date: 'Sun, 12 Sep 2021 00:00:00 GMT',
        dow: 6,
        severity: 0,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        date: 'Mon, 13 Sep 2021 00:00:00 GMT',
        dow: 0,
        severity: 2,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        date: 'Tue, 14 Sep 2021 00:00:00 GMT',
        dow: 1,
        severity: 0,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        date: 'Wed, 15 Sep 2021 00:00:00 GMT',
        dow: 2,
        severity: 4,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        date: 'Thu, 16 Sep 2021 00:00:00 GMT',
        dow: 3,
        severity: 5,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        date: 'Fri, 17 Sep 2021 00:00:00 GMT',
        dow: 4,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Sat, 18 Sep 2021 00:00:00 GMT',
        dow: 5,
        severity: 0,
        topic_id: null,
        topic_name: null,
      },
      {
        date: 'Sun, 19 Sep 2021 00:00:00 GMT',
        dow: 6,
        severity: 3,
        topic_id: null,
        topic_name: null,
      },
    ],
    weekly_commitment: [
      {
        did_commitment: false,
        is_future: false,
        topic_id: 27,
        topic_name: 'Grounding ',
      },
      {
        did_commitment: false,
        is_future: true,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        did_commitment: false,
        is_future: true,
        topic_id: 32,
        topic_name: 'Compassion',
      },
    ],
    weekly_meeting_attendance: [
      {
        attendance: 'half',
        did_attend_meeting: true,
        is_future: false,
        meeting_id: 93142185142,
        topic_id: 27,
        topic_name: 'Grounding ',
      },
      {
        attendance: 'half',
        did_attend_meeting: true,
        is_future: true,
        meeting_id: 86569789961,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        attendance: null,
        did_attend_meeting: false,
        is_future: true,
        meeting_id: 85975657995,
        topic_id: 32,
        topic_name: 'Compassion',
      },
    ],
    weekly_power_up: [
      {
        did_power_up: false,
        is_future: false,
        topic_id: 27,
        topic_name: 'Grounding ',
      },
      {
        did_power_up: true,
        is_future: true,
        topic_id: 30,
        topic_name: 'Addiction',
      },
      {
        did_power_up: false,
        is_future: true,
        topic_id: 32,
        topic_name: 'Compassion',
      },
    ],
  },
};
