export enum ProgressRoutes {
  MAIN = 'Progress-Main',
  SEND_REPORT = 'Progress-SendReport',
  // TREE_PROGRESS = 'Progress-TreeProgress',
  DAILY_ACTIONS = 'Progress-DailyActions',
  PREPARE_AHEAD = 'Progress-TriggerPrepareAhead',
  BOOMERANG = 'Progress-SafetyBoomerang',
  SOCIAL_FEED = 'Progress-ReachOutSocialFeed',
  SAFE_PLACE = 'Progress-SafetySafePlace',
  PLAN = 'Progress-SafetyPlan',
  SURPRISE = 'Progress-SafetySurprise',
  TALK_TO_SELF = 'Progress-SafetyTalkToSelf',
  PICTURE = 'Progress-SafetyProgress',
  AR_TREE = 'Progress-ArTree',
}
