import { Boomerang } from 'model/backend/safety';

export const BOOMERANGS: Boomerang[] = [
  {
    goal: 'Get exercise every day',
    id: 588,
    is_content_chosen: true,
    is_weekly: true,
    is_when_random: true,
    link: 'Contact your Trusted People',
    message: '',
    reminder: 'Courage, dear heart',
    scheduled_event: {
      end_at: 'Thu, 17 Jun 2021 13:15:54 GMT',
      event_name: null,
      event_type: null,
      id: 2680,
      invitees: [
        {
          id: 2623,
          invitee_id: 'dc27720c-b99f-11eb-b0b9-16e2a3977c87',
          invitee_type: 'user',
          is_deleted: false,
          scheduled_event_id: 2680,
        },
      ],
      is_deleted: false,
      repeats: [
        {
          id: 1061,
          interval_seconds: null,
          scheduled_event_id: 2680,
          to_char_pattern: 'D',
          to_char_value: 5,
        },
      ],
      resource_id: '588',
      resource_type: 'boomerang',
      start_at: 'Thu, 17 Jun 2021 12:15:54 GMT',
    },
    user_uuid: 'dc27720c-b99f-11eb-b0b9-16e2a3977c87',
  },
  {
    goal: 'Breathe deeply',
    id: 593,
    is_content_chosen: true,
    is_weekly: true,
    is_when_random: true,
    link: 'Go to Daily Reflections',
    message: 'Test',
    reminder: 'Make wise choices',
    scheduled_event: {
      end_at: 'Sun, 11 Jul 2021 23:29:30 GMT',
      event_name: null,
      event_type: null,
      id: 2811,
      invitees: [
        {
          id: 2754,
          invitee_id: 'dc27720c-b99f-11eb-b0b9-16e2a3977c87',
          invitee_type: 'user',
          is_deleted: false,
          scheduled_event_id: 2811,
        },
      ],
      is_deleted: false,
      repeats: [
        {
          id: 1098,
          interval_seconds: null,
          scheduled_event_id: 2811,
          to_char_pattern: 'D',
          to_char_value: 1,
        },
      ],
      resource_id: '593',
      resource_type: 'boomerang',
      start_at: 'Sun, 11 Jul 2021 22:29:30 GMT',
    },
    user_uuid: 'dc27720c-b99f-11eb-b0b9-16e2a3977c87',
  },
  {
    goal: 'Be patient with my kids',
    id: 594,
    is_content_chosen: false,
    is_weekly: true,
    is_when_random: true,
    link: 'Contact your Trusted People',
    message: null,
    reminder: 'Courage, dear heart',
    scheduled_event: {
      end_at: 'Tue, 06 Jul 2021 22:07:15 GMT',
      event_name: null,
      event_type: null,
      id: 2815,
      invitees: [
        {
          id: 2758,
          invitee_id: 'dc27720c-b99f-11eb-b0b9-16e2a3977c87',
          invitee_type: 'user',
          is_deleted: false,
          scheduled_event_id: 2815,
        },
      ],
      is_deleted: false,
      repeats: [
        {
          id: 1099,
          interval_seconds: null,
          scheduled_event_id: 2815,
          to_char_pattern: 'D',
          to_char_value: 3,
        },
      ],
      resource_id: '594',
      resource_type: 'boomerang',
      start_at: 'Tue, 06 Jul 2021 21:07:15 GMT',
    },
    user_uuid: 'dc27720c-b99f-11eb-b0b9-16e2a3977c87',
  },
  {
    goal: 'Today, abstinence',
    id: 595,
    is_content_chosen: false,
    is_weekly: true,
    is_when_random: true,
    link: 'Go to Safety main menu',
    message: null,
    reminder: 'No feeling is final',
    scheduled_event: {
      end_at: 'Fri, 09 Jul 2021 14:39:13 GMT',
      event_name: null,
      event_type: null,
      id: 2822,
      invitees: [
        {
          id: 2765,
          invitee_id: 'dc27720c-b99f-11eb-b0b9-16e2a3977c87',
          invitee_type: 'user',
          is_deleted: false,
          scheduled_event_id: 2822,
        },
      ],
      is_deleted: false,
      repeats: [
        {
          id: 1106,
          interval_seconds: null,
          scheduled_event_id: 2822,
          to_char_pattern: 'D',
          to_char_value: 6,
        },
      ],
      resource_id: '595',
      resource_type: 'boomerang',
      start_at: 'Fri, 09 Jul 2021 13:39:13 GMT',
    },
    user_uuid: 'dc27720c-b99f-11eb-b0b9-16e2a3977c87',
  },
  {
    goal: "Notice what's good about me",
    id: 596,
    is_content_chosen: false,
    is_weekly: true,
    is_when_random: true,
    link: 'Make a Safety Plan',
    message: null,
    reminder: 'No feeling is final',
    scheduled_event: {
      end_at: 'Sun, 18 Jul 2021 16:30:27 GMT',
      event_name: null,
      event_type: null,
      id: 2839,
      invitees: [
        {
          id: 2782,
          invitee_id: 'dc27720c-b99f-11eb-b0b9-16e2a3977c87',
          invitee_type: 'user',
          is_deleted: false,
          scheduled_event_id: 2839,
        },
      ],
      is_deleted: false,
      repeats: [
        {
          id: 1116,
          interval_seconds: null,
          scheduled_event_id: 2839,
          to_char_pattern: 'D',
          to_char_value: 1,
        },
      ],
      resource_id: '596',
      resource_type: 'boomerang',
      start_at: 'Sun, 18 Jul 2021 15:30:27 GMT',
    },
    user_uuid: 'dc27720c-b99f-11eb-b0b9-16e2a3977c87',
  },
];
